### PR TITLE
Add nonnull annotation

### PR DESCRIPTION
**Pull request by casz**
Downstream of https://github.com/jenkinsci/display-url-api-plugin/pull/19

### CODE REVIEW

**Comment by casz** [comment]
hmm yes the snapshot was built with Java 8 but targeting java level 6 has not changed :|

**Comment by halkeye** [comment]
Btw, your build is failing with:

[WARNING] Rule 2: org.apache.maven.plugins.enforcer.EnforceBytecodeVersion failed with message:

Found Banned Dependency: org.jenkins-ci.plugins:display-url-api:jar:2.2.1-SNAPSHOT

**Comment by halkeye** [comment]
Targeting java 8 should be fine, I know there's a blog somewhere but jenkins has generally gone up to 8 now.

**Comment by halkeye** [comment]
rebase/fix conflict and maybe the build will work? i did a bunch of upgrades and cleanups

**Comment by casz** [comment]
@halkeye done, done :+1: hopefully you can help push https://github.com/jenkinsci/display-url-api-plugin/pull/19 along

**Comment by casz** [comment]
:wave: @halkeye this should be ready for review again :)

**Comment by oleg-nenashev** [comment]
No strong opinion here, whatever works

**Pull request merged**
