### PR TITLE
[JENKINS-44627] blueocean-display-url tests are failing if run in systems without git user.name 

### PR DESCRIPTION
**Pull request by raul-arabaolaza**
[JENKINS-44627](https://issues.jenkins-ci.org/browse/JENKINS-44627)

@reviewbybees specially @i386

### CODE REVIEW

**Comment by jglick** [comment]
The [official version](https://github.com/jenkinsci/git-plugin/blob/a274696e296172e4038fd9b1576e78b28998732d/src/test/java/jenkins/plugins/git/GitSampleRepoRule.java#L67-L68) BTW. Which among other things will allow us to delete some other copied-and-pasted stuff, critically picking up https://github.com/jenkinsci/workflow-scm-step-plugin/pull/13 without which you cannot reliably do tests on Windows. So fix this mess please.

**Comment by i386** [comment]
@vivek do you know why we've copied this code from the git plugin in both rest-impl in Blue Ocean and this plugin instead of depending on the test jar artifact for this?

**Comment by vivek** [comment]
@i386 don't remember why, probably there was some issue getting it to work back then due to some issue, probably happened when pipeline impl was split off rest-impl. We should definitely be doing test jar dependency on rest-impl, remove from pipeline-imll and keep them at one place.

**Comment by vivek** [comment]
@i386 In fact, I think we forgot to remove GitSampleRepoRule from rest-impl. No tests are using it over there.

**Comment by vivek** [comment]
@i386 @jglick probably a mistake, maybe didn't know if there was test jar from git plugin that could be used. We should probably be using it.

**Comment by vivek** [comment]
Replaced by https://github.com/jenkinsci/blueocean-display-url-plugin/pull/7.

**Comment by recena** [comment]
It seems we have forgotten  to say thanks you @raul-arabaolaza for addressing these details

**Pull request closed without merging**
